import string, math
print('|**| FICHA CATALOGRÁFICA AUTOMÁTICA |**|')
print('       |**| TIPO: LITERATURA |**|')
NumCutter = input('Número do Cutter......: ')
PriNome   = input('Primeiro nome do autor: ')
Sobrenome = input('Sobrenome do autor....: ')
Titulo    = input('Título da obra........: ')
Edicao    = input('Edição................: ')
DataPubli = input('Data de Publicação....: ')
DataPubli = DataPubli + ' '
NumPags   = input('Número de Páginas.....: ')
NumISBN   = input('Número do ISBN........: ')
Categoris = input('Categorias............: ')
CDD       = input('Número do CDD.........: ')
print('')
print('')
print('          Dados internacionais de Catalogação-na-Publicação (CIP)')
print('')
print(' {} {}, {}'.format(NumCutter.upper()[0:5]+NumCutter.lower()[-1], Sobrenome.upper(), PriNome))
print('        {} / {} {} - {}ª - Publicado em {}'.format(Titulo, PriNome, Sobrenome, Edicao, DataPubli))
print('')
print('            {} páginas.'.format(NumPags))
print('')
print('        Título Original: {}'.format(Titulo))
print('')
print('        ISBN: {}'.format(NumISBN))
print('')
print('        {}ª edição - {}'.format(Edicao, DataPubli[-5:-1]))
print('            {}'.format(Categoris))
print('')
print('                                                       CDD: {}'.format(CDD))
